### ISSUE TITLE
encryptStringWithPublicKey is not a function

### ISSUE THREAD

**Issue by kevinvn1709** [Touna-App-Front-End/react-native-rsa-util#1]
Hi @simman , I'm very interesting in and appreciate your project. I do follow your README but it does not work! Please view my error below.

![image](https://cloud.githubusercontent.com/assets/1281425/19375935/6292da62-9203-11e6-8129-598be4e8d6bb.png)

I had read your source code in node_modules, maybe you did not add index.js.

Please show me how can I use your library.

Thanks

**Comment by kevinvn1709** [comment]
Add Screenshot mobile

![image](https://cloud.githubusercontent.com/assets/1281425/19376002/ff0f8d2c-9203-11e6-93bc-f8eb829091d6.png)

**Comment by 0xLevin** [comment]
@kevinvn1709 , please update this modules.

**Comment by kevinvn1709** [comment]
Sorry @simman. I updated your module. The error has gone, but I got undefined data, event that I encrypt and decrypt own data by myself

```
const privateKey = `MIICXAIBAAKBgQC+tQPXWclMkq9pShIStm3TphKuktq+LXtxyTLDGhMC3FXQ8/Sw
lx6Fg/5MC5jmbTDfJA9iYUzsY+djdqoWyyjF7A4B5fpZP//k+Nlm/SZ6vUSm1Hko
zDWvm/33RPcwicLBXf6zaW9OOCiWd28CGCXU8Ok/eKaXGyZF4JzvWpYiIwIDAQAB
AoGABv1XcLMnv5i4uSEv3GO3TsSNdryHK+U62wbGx4PTIo20z33BgB9pzPbzgRID
vp5N5j/KGI78ZMWcm3aj8UXs7pPuHDs8HOoBUD0Dzk+HnMXK7/vKTK8d/mt23zrs
VWv29aAIlvi3ey0v1M1yVs4nAm4ybdjjP9O0fEgPXs7+MOECQQDjlsHBJsGnCl9w
ZPW8xUHfLv2Mmaon0DY4cVuqj+5GwPsk9vJd/YikrSP3HZFObkBQIFXpbzJ9htvI
E99tVq6ZAkEA1oOYrFtbQwh3bgTSGFCQUyNTuk62H/RWfTQS/f5ZdsNdB/tIr4as
I65kgoqKGeImTEiWgGRK73Dyq6Zil6p4GwJBAJkplwFvHLpW373bJAnDUr5peFdL
/thGZob7uu4BaSEStLG+w4N/oZr5ro+axXRb/EowSMENhZQ20uhGf4Gs6VkCQGmY
jB5ENm+QCmJxIw7vEayrVjr/Ji4itDSb3sGDZHzO/MvCCezFyZUi8r1D/2lwZtPk
Y5m+RRkLK5oNpLjuJIMCQDspMDL2uUpkDzAhH6xFxYlHCSADSks3Ls2brW/b5xFN
ricGPpZGbqSjeYXDuVvprHRXZTthhitKbC8p1W0BGnw=`;

const encrypted = 'pQybyYHJQlIh9t5dbd3Kyuuxh/ya6THPVqX3AUPRfdmY28R90RkXxITJv4xblIjeemaUb67uv+ktowMnGhN0S67hnlVD6nop1jFgeX/+HGzXo2V61aW86JYjvmPLdTwsHeWFQfgR4cdA+SPHVZTUmcey2Qrq7D1ZBVFIMusyXgY=';
    ReactNativeRSAUtil.decryptStringWithPrivateKey(encrypted, privateKey)
      .then((error, data) => {
        if (!error) {
          console.log(data);
        } else {
          console.log(error);
        }
      });
```

Please help. Correct me if anything wrong

Thanks

**Comment by 0xLevin** [comment]
@kevinvn1709 , see #2

**Comment by kevinvn1709** [comment]
@simman: It does not work for me and I find out your example code is not correct, in Native Code you return a Promise so in JS React Code It should be 

```
ReactNativeRSAUtil.encryptStringWithPrivateKey('Hello', privateKey)
      .then((data) => {
        console.log(data);
      }, error => {
        console.log(error);
      });
```

instead of

```
ReactNativeRSAUtil.decryptStringWithPrivateKey(encrypted, privateKey)
      .then((error, data) => {
        if (!error) {
          console.log(data);
        } else {
          console.log(error);
        }
      });
```

I am trying many ways to use your lib but It seems not work. I have no idea to put private or public key format in your parameters

It is still a great and lightweight library RSA, I hope you can improve guides or example that we can use it.

**Comment by sreeksp** [comment]
@kevinvn1709 did you find any module that does rsa decryption with private key?
